### ISSUE TITLE
您好，请教下基于http2的代理如何实现

### ISSUE THREAD

**Issue by yeyincai** [Rearcher/netty-demos#1]
开发的rpc是采用google的grpc，grpc是基于http2，我们想用netty做个类似nginx代理，实现负载和限流等功能，研究了比较久没整出来

**Comment by Rearcher** [comment]
您好，http2我目前还没有了解过，所以也不是太清楚，个人能力不足，无法为您解答，抱歉。或许可以Google以下，这个项目看起来不错https://github.com/twitter/netty-http2

**Comment by Rearcher** [comment]
不知道使用http2相关的codec是否可行？

**Comment by yeyincai** [comment]
http2的codec可以解码，能拿到信息，但是传给服务端就不行
